name: readmission-prediction-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - pip<=23.3.1
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib
  - seaborn
  - scikit-learn=1.2.2
  - psutil
  - scipy
  - pip:
      - mlflow==2.11.3
      - imbalanced-learn==0.11.0
      - xgboost==2.0.3
      - sklearn-features==0.0.2
